#server.port=8080
#
#sf.client.id=YOUR_CLIENT_ID
#sf.client.secret=YOUR_CLIENT_SECRET
#sf.redirect.uri=http://localhost:8080/auth/callback
#sf.auth.url=https://login.salesforce.com

server.port=8080

sf.client.id= CONSUMER_KEY
sf.client.secret=CONSUMER_SECRET

sf.redirect.uri=http://localhost:8080/auth/callback

sf.auth.url=https://login.salesforce.com